name: fluctuation
description: A flutter toolkit for multi-platform application development.
version: 0.0.0
environment: {sdk: ^3.1.5}

dependencies:
  flutter: {sdk: flutter}

dev_dependencies:
  test: ^1.21.0
  fluctuation_lints: {path: ./lints}
