name: fluctuation_gen
description: Code generator for fluctuation.
version: 0.0.0
publish_to: "none"
environment: {sdk: ^3.1.5}

dependencies:
  # Relative path import is not available here.
  fluctuation_anno:
    git:
      url: https://github.com/hilltwice233/fluctuation.git
      ref: main # Sync with latest because inside the monorepo.
      path: anno

  analyzer: ^6.2.0
  build: ^2.4.1
  source_gen: ^1.4.0

dev_dependencies:
  fluctuation_lints: {path: ../lints}
